
package Vista;

import Controlador.ControladorInicialAdivLaPal;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class VistaPrincipalAdivLaPal extends javax.swing.JFrame {

    public VistaPrincipalAdivLaPal() {
        initComponents();
        this.setTitle(ControladorInicialAdivLaPal.titulo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonFacil = new javax.swing.JButton();
        botonNormal = new javax.swing.JButton();
        botonDificil = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonInstrucciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adivina la palabra");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Elija una dificultad:");

        botonFacil.setText("Fácil (5 letras)");
        botonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacilActionPerformed(evt);
            }
        });

        botonNormal.setText("Normal (6 letras)");

        botonDificil.setText("Difícil (7 letras)");

        botonSalir.setText("Salir");

        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFacil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonDificil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(botonSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(botonInstrucciones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(botonFacil)
                .addGap(18, 18, 18)
                .addComponent(botonNormal)
                .addGap(18, 18, 18)
                .addComponent(botonDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(botonInstrucciones)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFacilActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDificil;
    private javax.swing.JButton botonFacil;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JButton botonNormal;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void mostrarInstrucciones(){
        JOptionPane.showMessageDialog(null,"El objetivo del juego es adivinar una palabra al azar."
                + "\nPara lograr esto debe ingresar letras mediante el teclado en pantalla"
                + "\no el teclado real. Al validar el intento (presionando OK o Enter)"
                + "\nse indicarán por pantalla sus aciertos. Si la letra se marca con un fondo verde"
                + "\nsignifica que esa letra está en la palabra a adivinar, en esa posición exacta."
                + "\nSi la letra se marca con un círculo verde, la letra está en la palabra, pero no"
                + "\nen esa posición. Use estos indicadores para llegar a adivinar la palabra.","Instrucciones",JOptionPane.INFORMATION_MESSAGE);
    }

    public JButton getBotonDificil() {
        return this.botonDificil;
    }
    public JButton getBotonFacil() {
        return this.botonFacil;
    }
    public JButton getBotonInstrucciones() {
        return this.botonInstrucciones;
    }
    public JButton getBotonNormal() {
        return this.botonNormal;
    }
    public JButton getBotonSalir() {
        return this.botonSalir;
    }
    
    public void agregarListener(ActionListener al){
        this.botonDificil.addActionListener(al);
        this.botonFacil.addActionListener(al);
        this.botonNormal.addActionListener(al);
        this.botonInstrucciones.addActionListener(al);
        this.botonSalir.addActionListener(al);
    }
}
