
package Vista;

import Controlador.ControladorInicialAdivLaPal;
import Controlador.ControladorJuegoAdivLaPal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

public class VistaJuegoAdivLaPal extends javax.swing.JFrame {

    public VistaJuegoAdivLaPal() {
        initComponents();
        this.setTitle(ControladorInicialAdivLaPal.titulo);
        textoInfoJuego.append("Ingrese "+ControladorJuegoAdivLaPal.cantidadLetras+" letras.\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelTeclado1 = new javax.swing.JPanel();
        panelTeclado2 = new javax.swing.JPanel();
        panelTeclado3 = new javax.swing.JPanel();
        panelBotonBorrar = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonOk = new javax.swing.JButton();
        displayTexto = new javax.swing.JScrollPane();
        textoInfoJuego = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(825, 660));

        panelTablero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        panelTablero.setLayout(new java.awt.GridLayout(5,Controlador.ControladorJuegoAdivLaPal.cantidadLetras,0,5));

        for (int i=0; i<5; i++){
            for (int j=0; j<Controlador.ControladorJuegoAdivLaPal.cantidadLetras; j++){
                tablero[i][j] = new JLabel();
                tablero[i][j].setFont(new java.awt.Font("Tahoma", 1, 60));
                tablero[i][j].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                tablero[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoCasilla.png")));
                tablero[i][j].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                tablero[i][j].setBorder(bordeLabels);
                tablero[i][j].setOpaque(false);
                panelTablero.add(tablero[i][j]);
            }
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(505, 180));

        panelTeclado1.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout panelTeclado1Layout = new javax.swing.GroupLayout(panelTeclado1);
        panelTeclado1.setLayout(panelTeclado1Layout);
        panelTeclado1Layout.setHorizontalGroup(
            panelTeclado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        panelTeclado1Layout.setVerticalGroup(
            panelTeclado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelTeclado1.setLayout(new java.awt.GridLayout(1,10));

        for (int i=0; i<10; i++){
            tecladoFila1[i] = new JButton();
            tecladoFila1[i].setFont(new java.awt.Font("Tahoma", 1, 36));
            tecladoFila1[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila1[i].setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila1[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoTeclas.png")));
            tecladoFila1[i].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila1[i].setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila1[i].setText(tecladoLetras1[i]);
            tecladoFila1[i].setBorder(bordeLabels);
            panelTeclado1.add(tecladoFila1[i]);
        }

        javax.swing.GroupLayout panelTeclado2Layout = new javax.swing.GroupLayout(panelTeclado2);
        panelTeclado2.setLayout(panelTeclado2Layout);
        panelTeclado2Layout.setHorizontalGroup(
            panelTeclado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        panelTeclado2Layout.setVerticalGroup(
            panelTeclado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelTeclado2.setLayout(new java.awt.GridLayout(1,9));

        for (int i=0; i<9; i++){
            tecladoFila2[i] = new JButton();
            tecladoFila2[i].setFont(new java.awt.Font("Tahoma", 1, 36));
            tecladoFila2[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila2[i].setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila2[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoTeclas.png")));
            tecladoFila2[i].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila2[i].setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila2[i].setText(tecladoLetras2[i]);
            tecladoFila2[i].setBorder(bordeLabels);
            panelTeclado2.add(tecladoFila2[i]);
        }

        javax.swing.GroupLayout panelTeclado3Layout = new javax.swing.GroupLayout(panelTeclado3);
        panelTeclado3.setLayout(panelTeclado3Layout);
        panelTeclado3Layout.setHorizontalGroup(
            panelTeclado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelTeclado3Layout.setVerticalGroup(
            panelTeclado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelTeclado3.setLayout(new java.awt.GridLayout(1,7));

        for (int i=0; i<7; i++){
            tecladoFila3[i] = new JButton();
            tecladoFila3[i].setFont(new java.awt.Font("Tahoma", 1, 36));
            tecladoFila3[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila3[i].setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            tecladoFila3[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoTeclas.png")));
            tecladoFila3[i].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila3[i].setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
            tecladoFila3[i].setText(tecladoLetras3[i]);
            tecladoFila3[i].setBorder(bordeLabels);
            panelTeclado3.add(tecladoFila3[i]);
        }

        panelBotonBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoTeclaBorrar.png"))); // NOI18N
        botonBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelBotonBorrarLayout = new javax.swing.GroupLayout(panelBotonBorrar);
        panelBotonBorrar.setLayout(panelBotonBorrarLayout);
        panelBotonBorrarLayout.setHorizontalGroup(
            panelBotonBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotonBorrarLayout.setVerticalGroup(
            panelBotonBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelTeclado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(panelTeclado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(panelBotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelTeclado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelTeclado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelTeclado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panelTeclado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(290, 180));

        botonOk.setText("OK");

        textoInfoJuego.setEditable(false);
        textoInfoJuego.setColumns(20);
        textoInfoJuego.setRows(5);
        displayTexto.setViewportView(textoInfoJuego);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOk)
                .addGap(117, 117, 117))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayTexto)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonOk;
    private javax.swing.JScrollPane displayTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBotonBorrar;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JPanel panelTeclado1;
    private javax.swing.JPanel panelTeclado2;
    private javax.swing.JPanel panelTeclado3;
    private javax.swing.JTextArea textoInfoJuego;
    // End of variables declaration//GEN-END:variables

    Border bordeLabels = BorderFactory.createLineBorder(Color.black);
    private JLabel[][] tablero = new JLabel[5][ControladorJuegoAdivLaPal.cantidadLetras];
    Dimension separador = new Dimension(60,2);
    private JButton[] tecladoFila1 = new JButton[10];
    private String[] tecladoLetras1 = {"Q","W","E","R","T","Y","U","I","O","P"};
    private JButton[] tecladoFila2 = new JButton[9];
    private String[] tecladoLetras2 = {"A","S","D","F","G","H","J","K","L"};
    private JButton[] tecladoFila3 = new JButton[7];
    private String[] tecladoLetras3 = {"Z","X","C","V","B","N","M"};
    
    public void mostrarLetra(char letra){
        String texto;
        texto = Character.toString(letra);
        tablero[ControladorJuegoAdivLaPal.cantidadIntentos][ControladorJuegoAdivLaPal.indiceLetra].setText(texto.toUpperCase());
    }
    
    public void mostrarLetra(boolean falso){
        tablero[ControladorJuegoAdivLaPal.cantidadIntentos][ControladorJuegoAdivLaPal.indiceLetra].setText(null);
    }
    
    public void mostrarAciertos(ArrayList<Integer> indicesLetrasCorrectas, ArrayList<Integer> indicesLetrasEncontradas){
        for(Integer indice:indicesLetrasCorrectas){
            tablero[ControladorJuegoAdivLaPal.cantidadIntentos][indice].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoLetraCorrecta.png")));
        }
        for(Integer indice:indicesLetrasEncontradas){
            tablero[ControladorJuegoAdivLaPal.cantidadIntentos][indice].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AdivLaPal/FondoLetraExiste.png")));
        }
    }
    
    public JButton getBotonOk(){
        return botonOk;
    }
    public JButton getBotonBorrar(){
        return botonBorrar;
    }
    public JButton getLetraQ(){
        return tecladoFila1[0];
    }
    public JButton getLetraW(){
        return tecladoFila1[1];
    }
    public JButton getLetraE(){
        return tecladoFila1[2];
    }
    public JButton getLetraR(){
        return tecladoFila1[3];
    }
    public JButton getLetraT(){
        return tecladoFila1[4];
    }
    public JButton getLetraY(){
        return tecladoFila1[5];
    }
    public JButton getLetraU(){
        return tecladoFila1[6];
    }
    public JButton getLetraI(){
        return tecladoFila1[7];
    }
    public JButton getLetraO(){
        return tecladoFila1[8];
    }
    public JButton getLetraP(){
        return tecladoFila1[9];
    }
    public JButton getLetraA(){
        return tecladoFila2[0];
    }
    public JButton getLetraS(){
        return tecladoFila2[1];
    }
    public JButton getLetraD(){
        return tecladoFila2[2];
    }
    public JButton getLetraF(){
        return tecladoFila2[3];
    }
    public JButton getLetraG(){
        return tecladoFila2[4];
    }
    public JButton getLetraH(){
        return tecladoFila2[5];
    }
    public JButton getLetraJ(){
        return tecladoFila2[6];
    }
    public JButton getLetraK(){
        return tecladoFila2[7];
    }
    public JButton getLetraL(){
        return tecladoFila2[8];
    }
    public JButton getLetraZ(){
        return tecladoFila3[0];
    }
    public JButton getLetraX(){
        return tecladoFila3[1];
    }
    public JButton getLetraC(){
        return tecladoFila3[2];
    }
    public JButton getLetraV(){
        return tecladoFila3[3];
    }
    public JButton getLetraB(){
        return tecladoFila3[4];
    }
    public JButton getLetraN(){
        return tecladoFila3[5];
    }
    public JButton getLetraM(){
        return tecladoFila3[6];
    }
    
    public void setTextArea(String texto){
        this.textoInfoJuego.append(texto+"\n");
    }

    public void agregarListener(ActionListener al){
        this.botonOk.addActionListener(al);
        this.botonBorrar.addActionListener(al);
        for (int i=0; i<10; i++){
            tecladoFila1[i].addActionListener(al);
        }
        for (int j=0; j<9; j++){
            tecladoFila2[j].addActionListener(al);
        }
        for (int k=0; k<7; k++){
            tecladoFila3[k].addActionListener(al);
        }
    }
    
    public void agregarKeyListener(KeyListener kl){
        this.botonBorrar.addKeyListener(kl);
        this.botonOk.addKeyListener(kl);
        for (int i=0; i<10; i++){
            tecladoFila1[i].addKeyListener(kl);
        }
        for (int j=0; j<9; j++){
            tecladoFila2[j].addKeyListener(kl);
        }
        for (int k=0; k<7; k++){
            tecladoFila3[k].addKeyListener(kl);
        }
    }
    
    public void marcarCasilla(){
        if(ControladorJuegoAdivLaPal.cantidadIntentos < 5){
            Border borde = new LineBorder(Color.RED,1);
            if(ControladorJuegoAdivLaPal.indiceLetra != ControladorJuegoAdivLaPal.cantidadLetras){
                tablero[ControladorJuegoAdivLaPal.cantidadIntentos][ControladorJuegoAdivLaPal.indiceLetra].setBorder(borde);
                if(ControladorJuegoAdivLaPal.indiceLetra > 0){
                    tablero[ControladorJuegoAdivLaPal.cantidadIntentos][ControladorJuegoAdivLaPal.indiceLetra-1].setBorder(bordeLabels);
                }
            }
            for(int i=ControladorJuegoAdivLaPal.indiceLetra+1; i<ControladorJuegoAdivLaPal.cantidadLetras; i++){
                tablero[ControladorJuegoAdivLaPal.cantidadIntentos][i].setBorder(bordeLabels);
            }
            if(ControladorJuegoAdivLaPal.cantidadIntentos > 0){
                for(int j=0; j<ControladorJuegoAdivLaPal.cantidadLetras; j++){
                    tablero[ControladorJuegoAdivLaPal.cantidadIntentos-1][j].setBorder(bordeLabels);
                }
            }
        }
    }

}
