/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Nicolas
 */
public class VistaTableroBuscaminas extends javax.swing.JFrame {
    //Atributos
    private int rango;   
    private JButton[][] mapa1;
    
    //Constructor
    public VistaTableroBuscaminas(int rango, int numeroMin) {
        //this.rango = rango;
        initComponents();
        construirTablero(rango, numeroMin);
        if (rango == 10){
            this.setSize(900,735);
            Panel.setSize(620,620);
        }
        if (rango == 20){
            this.setSize(1100, 735);
            Panel.setSize(620,620);
        }
        if (rango == 30){
            this.setSize(1400, 735);
            Panel.setSize(620,620);
        }
        
    }
    
    //Métodos get y set//
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroMinas = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Panel.setMaximumSize(new java.awt.Dimension(620, 620));
        Panel.setMinimumSize(new java.awt.Dimension(620, 620));
        Panel.setPreferredSize(new java.awt.Dimension(620, 620));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Minas Restantes:");

        numeroMinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroMinas.setText("??");
        numeroMinas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(numeroMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public int getRango() {
        return rango;
    }
    public JPanel getPanel() {
        return Panel;
    }
    public JButton[][] getMapa1() {
        return mapa1;
    }
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setNumeroMinas(int numero) {
      numeroMinas.setText(Integer.toString(numero));
    }

    public void setPanel(JPanel Panel) {
        this.Panel = Panel;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numeroMinas;
    // End of variables declaration//GEN-END:variables

    //Metodos
    public JButton[][] construirTablero(int rango, int numeroMin){
        this.rango=rango;//Se iguala el parametro al atributo
        this.Panel.setLayout(new GridLayout(rango,rango));
        mapa1 = new JButton [rango][rango];
        setNumeroMinas(numeroMin);
        for(int i=0; i<rango; i++){
            for(int j=0; j<rango; j++){
                mapa1[i][j] = new JButton();
                Dimension tamaño = new Dimension(15,15);
                mapa1[i][j].setPreferredSize(tamaño);
                mapa1[i][j].setMaximumSize(tamaño);
                mapa1[i][j].setMinimumSize(tamaño);
                mapa1[i][j].setBorderPainted(true);
                mapa1[i][j].setMargin(new Insets(0,0,0,0));
                if(rango == 20){
                    //mapa1[i][j].setSize(1000, 1000);
                    //Panel.setSize(1000, 1000);
                }
                Panel.add(mapa1[i][j]);
            }
        }
        //System.out.println(this.mapa1[0][0].getPreferredSize());
        //System.out.println(this.mapa1[0][0].getMaximumSize());
        //System.out.println(this.mapa1[0][0].getMinimumSize());
    return mapa1;
    }
    
    public void bListener(MouseListener s){
        btnCancelar.addMouseListener(s);
        for(int i=0; i < rango; i++){
            for(int j=0; j < rango; j++){
                mapa1[i][j].addMouseListener(s);
            }
        }
    }
    public void pintarCasillas(int i,int j){
        mapa1[i][j].setBackground(Color.red);
    }
    public void posicionarMina(int i, int j, int opcion){
        if(opcion == 0){
            mapa1[i][j].setText("x");
            
            String ruta = "";
            ImageIcon img = null;
            switch(rango){
            case 10:
                ruta = "src/Imagen/Buscaminas/minaFacil.png";
                img = new ImageIcon(ruta);
                break;
            case 20:
                ruta = "src/Imagen/Buscaminas/minaNormal.png";
                img = new ImageIcon(ruta);
                break;
            case 30:
                ruta = "src/Imagen/Buscaminas/minaDificil.png";
                img = new ImageIcon(ruta);
                break;
            }
            mapa1[i][j].setIcon(img);
        }
        else if(opcion == 1){
            mapa1[i][j].setText("");
            JButton boton = new JButton();
            Icon icono = boton.getIcon();
            mapa1[i][j].setIcon(icono);
        }
    }
    public void mostrar(int i, int j, int numero, boolean opcion){
        if(opcion == true){//Si hay un numero
            if(numero!=0){
                mapa1[i][j].setText("" + numero);
            }
            else{
                mapa1[i][j].setEnabled(false);
            }
        }
        else if(numero==0){//Si no hay nada
            mapa1[i][j].setText("");
            mapa1[i][j].setBackground(Color.BLACK);
        }
    }
    public boolean estadoGanador(){
        boolean respuesta = true;
        for(int i=0; i<rango; i++){
            for(int j=0; j<rango; j++){
                if(!(mapa1[i][j].toString()=="")){
                    respuesta = false;
                    break;
                }
            }
            if(respuesta == false){
                break;
            }
        }
        return respuesta;
    }
}

